# Hebrew for the English comments the US mintage sources attach to some rows (keys are the comment without a final period).
STATES = {'Alabama': 'אלבמה', 'Arkansas': 'ארקנסו', 'Connecticut': 'קונטיקט', 'Delaware': 'דלאוור', 'Florida': 'פלורידה', 'Georgia': 'ג׳ורג׳יה',
          'Illinois': 'אילינוי', 'Indiana': 'אינדיאנה', 'Kentucky': 'קנטקי', 'Louisiana': 'לואיזיאנה', 'Maine': 'מיין', 'Maryland': 'מרילנד',
          'Massachusetts': 'מסצ׳וסטס', 'Michigan': 'מישיגן', 'Mississippi': 'מיסיסיפי', 'Missouri': 'מיזורי', 'New Hampshire': 'ניו המפשייר',
          'New Jersey': 'ניו ג׳רזי', 'New York': 'ניו יורק', 'North Carolina': 'קרוליינה הצפונית', 'Ohio': 'אוהיו', 'Pennsylvania': 'פנסילבניה',
          'Rhode Island': 'רוד איילנד', 'South Carolina': 'קרוליינה הדרומית', 'Tennessee': 'טנסי', 'Texas': 'טקסס', 'Vermont': 'ורמונט',
          'Virginia': 'וירג׳יניה'}
NOTES_HE = {
    '"P" mintmark added to the obverse of the coin': 'סימן המטבעה P נוסף לצד הראשי של המטבע',
    '1,933,908,100 of these were struck in 1965': '1,933,908,100 מהם הוטבעו בפועל ב-1965',
    '932,780,000 of these were struck in 1965': '932,780,000 מהם הוטבעו בפועל ב-1965',
    '300,385,000 of these were struck in 1966': '300,385,000 מהם הוטבעו בפועל ב-1966',
    '25 over 50 overmark errors are known': 'ידועות טעויות הטבעה 25 על 50', '25 over 50 overmark errors known': 'ידועות טעויות הטבעה 25 על 50',
    '3 over 4 overdate errors are known': 'ידועות טעויות שנה 3 על 4', '5 over 2': 'שנה 5 על 2',
    '6 over 5 overdate errors are known': 'ידועות טעויות שנה 6 על 5', '8 over 5 overdate errors are known': 'ידועות טעויות שנה 8 על 5',
    '8 over 7 overdate errors are known': 'ידועות טעויות שנה 8 על 7', 'All are 3 over 2 overdate errors': 'כולם בטעות שנה 3 על 2',
    'Arrows at date; rays on reverse': 'חצים ליד השנה וקרניים בגב', 'Bicentennial Type I': 'מהדורת המאתיים, סוג I',
    'Bicentennial Type II': 'מהדורת המאתיים, סוג II',
    'Can be told apart from the non-silver nickels since these have a mintmark above Monticello': 'ניתן להבחין בינו לבין הניקל שאינו מכסף לפי סימן המטבעה מעל מונטיצ׳לו',
    'Continued to be struck until 1966': 'המשיך להיות מוטבע עד 1966', 'Double die variety has been found': 'נמצא וריאנט Doubled Die',
    'Doubled die errors are known': 'ידועות טעויות Doubled Die', 'Doubled-Die varieties have been found': 'נמצאו וריאנטים של Doubled Die',
    'Dwight D. Eisenhower': 'דווייט ד. אייזנהאואר', 'Error, many counterfeits exist': 'טעות; קיימים זיופים רבים',
    'Final year New Orleans produced the half dollar': 'השנה האחרונה שבה ניו אורלינס הטביעה חצי דולר',
    'First time Denver produced the cent': 'הפעם הראשונה שדנוור הטביעה סנט', 'First time Denver produced the quarter': 'הפעם הראשונה שדנוור הטביעה רבע דולר',
    'First time New Orleans produced the quarter': 'הפעם הראשונה שניו אורלינס הטביעה רבע דולר',
    'First time San Francisco produced the cent': 'הפעם הראשונה שסן פרנסיסקו הטביעה סנט',
    'First time San Francisco produced the quarter': 'הפעם הראשונה שסן פרנסיסקו הטביעה רבע דולר',
    'First time the "W" mint mark was used on a circulating coin': 'הפעם הראשונה שסימן המטבעה W הופיע על מטבע מחזור',
    'First time the P mint mark was used on the quarter': 'הפעם הראשונה שסימן המטבעה P הופיע על רבע דולר',
    'First time the W mint mark was used on the quarter': 'הפעם הראשונה שסימן המטבעה W הופיע על רבע דולר',
    'First year Carson City produced the half dollar': 'השנה הראשונה שקרסון סיטי הטביעה חצי דולר',
    'First year Denver produced the half dollar': 'השנה הראשונה שדנוור הטביעה חצי דולר',
    'First year New Orleans produced the half dollar': 'השנה הראשונה שניו אורלינס הטביעה חצי דולר',
    'First year San Francisco produced the half dollar': 'השנה הראשונה שסן פרנסיסקו הטביעה חצי דולר',
    'First year of issue': 'שנת ההנפקה הראשונה', 'Franklin D. Roosevelt': 'פרנקלין ד. רוזוולט', 'Franklin Pierce': 'פרנקלין פירס',
    'Highest mintage of the series': 'הכמות הגבוהה ביותר בסדרה', 'Second-highest mintage of the series': 'הכמות השנייה בגובהה בסדרה',
    'Included in 1824, all are 5 over 2 or 4 overdate errors': 'נכלל בכמות של 1824; כולם בטעות שנה 5 על 2 או על 4',
    'Included in 1849-O': 'נכלל בכמות של 1849-O', 'Includes 4 Over 3 variety': 'כולל את וריאנט 4 על 3',
    'Includes 8 Over 7 variety': 'כולל את וריאנט 8 על 7', 'Includes Micro-O variety': 'כולל את וריאנט ה-O הזעירה',
    'Includes doubled-die reverse': 'כולל Doubled Die בגב',
    'Includes the "D on S" variety, 1938 Buffalo nickels were only minted in Denver': 'כולל את וריאנט D על S; ניקל הביזון של 1938 הוטבע רק בדנוור',
    'Includes the rare "3 Legs" variety': 'כולל את הווריאנט הנדיר "3 רגליים"', 'Includes the rare "3 and 1/2 Legs" variety': 'כולל את הווריאנט הנדיר "3.5 רגליים"',
    'Incredibly rare, 5 known to exist': 'נדיר ביותר; ידועים 5 עותקים', 'Introductory': 'מטבע פתיחה', 'John F. Kennedy': 'ג׳ון פ. קנדי',
    'Key date': 'Key Date', 'Semi-key date': 'Semi-Key', 'Large S over small S overmark errors are known': 'ידועות טעויות S גדולה על S קטנה',
    'Last year of issue': 'שנת ההנפקה האחרונה', 'Many counterfeits exist': 'קיימים זיופים רבים', 'Medium and tall dates': 'שנה בגובה בינוני ובגובה רב',
    'Mint records do not state any were made. A single example is known to exist': 'לפי רישומי המטבעה לא הוטבע; ידוע עותק יחיד',
    'Mint records report a mintage of 4,000. Only 5 are known to exist': 'לפי רישומי המטבעה הוטבעו 4,000; ידועים 5 בלבד',
    'Mint sets only': 'בסטים של המטבעה בלבד',
    'Mintmarks suspended until 1968 to discourage coin collecting': 'סימני המטבעה הושעו עד 1968 כדי לרסן אספנות',
    'No arrows, no rays. Only four known to exist': 'בלי חצים ובלי קרניים; ידועים ארבעה בלבד',
    'No buffalo nickels were made in 1922. Production resumed in 1923': 'לא הוטבעו ניקלי ביזון ב-1922; הייצור חודש ב-1923',
    'No nickels minted during 1932 and 1933. Production resumes 1934': 'לא הוטבעו ניקלים ב-1932–1933; הייצור חודש ב-1934',
    'None are known to currently exist; they were most likely melted down': 'לא ידוע על עותק קיים; כנראה כולם הותכו',
    'None struck': 'לא הוטבע', 'O over F overmark errors are known': 'ידועות טעויות O על F',
    'Obv. Privy mark “V75” inside Rainbow Pool added to 2020 only': 'בצד הראשי סימן V75 בתוך בריכת הקשת, ב-2020 בלבד',
    'Only 2 1815 large cents were produced, because of copper shortages for the War of 1812': 'לא הוטבעו סנטים גדולים ב-1815 בגלל מחסור בנחושת במלחמת 1812',
    'Only S mintmarks for 1931. Semi-key date': 'ב-1931 רק סימן S; Semi-Key',
    'Only year cent has displayed P mint mark (to commemorate 225th anniversary of the Philadelphia mint)': 'השנה היחידה שבה הסנט נשא סימן P (225 שנה למטבעת פילדלפיה)',
    'Only year minted at the Denver Mint': 'השנה היחידה שבה הוטבע בדנוור', 'Only year minted at the San Francisco Mint, Key date': 'השנה היחידה שבה הוטבע בסן פרנסיסקו; Key Date',
    'Philadelphia half dollars do not show a mint mark; for mintage, see Type 2 immediately below': 'חצאי הדולר של פילדלפיה ללא סימן מטבעה; הכמות מופיעה בסוג 2',
    'Presidency': 'נשיאות', 'Professional Life': 'חיים מקצועיים', 'S over D overmark errors are known': 'ידועות טעויות S על D',
    'S over horizontal S overmark errors are known': 'ידועות טעויות S על S שוכבת',
    'Second and last year with rays on reverse of coin. Most 1867 shield nickels are of the "No Rays" variety': 'השנה השנייה והאחרונה עם קרניים בגב; רוב ניקלי המגן של 1867 הם ללא קרניים',
    'Small/large stars, 50 over 20, and Bearded Liberty varieties': 'וריאנטים: כוכבים קטנים/גדולים, 50 על 20 ו"חירות מזוקנת"',
    'The first time Carson City produced the quarter': 'הפעם הראשונה שקרסון סיטי הטביעה רבע דולר',
    'There are 15- and 16-star varieties': 'קיימים וריאנטים עם 15 ועם 16 כוכבים', 'Type 2, Without Rays': 'סוג 2, ללא קרניים',
    'Varieties include knobbed/pointed 6, 6 over 5, large/small stars, stem through/not through claw, and E over A in "States"': 'וריאנטים: 6 מעוגלת/מחודדת, 6 על 5, כוכבים גדולים/קטנים, גבעול דרך הטופר או לא, ו-E על A ב-States',
    'the Great Recession caused low mintage numbers not seen since the 1950s': 'המיתון הגדול הוריד את הכמויות לרמה שלא נראתה מאז שנות ה-50',
}
NOTES_HE.update(STATES)

def note_he(c):
    return NOTES_HE.get(c.strip().rstrip('.'), c)
